"""initial schema

Revision ID: 099234203802
Revises: 
Create Date: 2026-03-31 15:22:48.598660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '099234203802'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('communities',
    sa.Column('community_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('community_id', name=op.f('pk_communities'))
    )
    op.create_table('firmware_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('binary_path', sa.String(length=256), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firmware_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_firmware_versions_version'))
    )
    op.create_table('homes',
    sa.Column('home_id', sa.String(length=64), nullable=False),
    sa.Column('patient_name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('home_id', name=op.f('pk_homes'))
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.community_id'], name=op.f('fk_broadcasts_community_id_communities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('firmware_version', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_id', sa.String(length=64), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('heap', sa.Integer(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.home_id'], name=op.f('fk_devices_home_id_homes')),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_devices')),
    sa.UniqueConstraint('mac', name=op.f('uq_devices_mac'))
    )
    op.create_table('home_community',
    sa.Column('home_id', sa.String(length=64), nullable=False),
    sa.Column('community_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.community_id'], name=op.f('fk_home_community_community_id_communities')),
    sa.ForeignKeyConstraint(['home_id'], ['homes.home_id'], name=op.f('fk_home_community_home_id_homes')),
    sa.PrimaryKeyConstraint('home_id', 'community_id', name=op.f('pk_home_community'))
    )
    op.create_table('broadcast_acks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], name=op.f('fk_broadcast_acks_broadcast_id_broadcasts')),
    sa.ForeignKeyConstraint(['home_id'], ['homes.home_id'], name=op.f('fk_broadcast_acks_home_id_homes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_acks'))
    )
    op.create_table('ota_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('from_version', sa.String(length=32), nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name=op.f('fk_ota_events_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ota_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ota_events')
    op.drop_table('broadcast_acks')
    op.drop_table('home_community')
    op.drop_table('devices')
    op.drop_table('broadcasts')
    op.drop_table('homes')
    op.drop_table('firmware_versions')
    op.drop_table('communities')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
